monday_temp = [9.1, 4.5, 2.0]
monday_temp.append(7.0)
print(monday_temp)
monday_temp.remove(9.1)
print(monday_temp)
print(monday_temp.index(4.5))
monday_temp.clear()
print(monday_temp)
monday_temp.append(8.0)
monday_temp.append(8.0)
monday_temp.append(8.0)
monday_temp.append(8.0)
monday_temp.append(8.0)
print()
print(monday_temp.index(8.0, 2))
print(monday_temp.index(8.0, 3, 4)) # find 8.0, start from index of 2 and end with index of 3